version: '3.8'

# Simplified Docker Compose for local development
# For production deployment of monitoring stack, use otel-collector-deployment/

services:
  # Local Jaeger for development (optional)
  jaeger-dev:
    image: jaegertracing/all-in-one:1.50
    container_name: jaeger-dev
    ports:
      - "16686:16686" # Jaeger UI
      - "14250:14250" # gRPC
      - "14268:14268" # HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - dev-network
    profiles:
      - dev-tools

  # Local Prometheus for development (optional)
  prometheus-dev:
    image: prom/prometheus:v2.47.2
    container_name: prometheus-dev
    ports:
      - "9090:9090"   # Prometheus UI
    volumes:
      - ./prometheus-dev.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_dev_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=24h'
      - '--web.enable-lifecycle'
    networks:
      - dev-network
    profiles:
      - dev-tools

volumes:
  prometheus_dev_data:

networks:
  dev-network:
    driver: bridge