# Local Prometheus configuration for testing collector metrics
# This is used when running with local-testing profile

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape OpenTelemetry Collector internal metrics
  - job_name: 'otel-collector-internal'
    static_configs:
      - targets: ['otel-collector:8888']
    scrape_interval: 10s

  # Scrape OpenTelemetry Collector exported metrics
  - job_name: 'otel-collector-metrics'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 15s